{
 "title": "Anomalous Hosts",
 "tags": [ "Direct" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Hostname", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "Anomalous Hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \ndistinct(anomaly_host_detail.unit_name) as \"Host\",\ncount(anomalous_score) as \"Anomaly Count\",\navg(anomalous_score) as \"Avg Score\",\nmax(anomalous_score) as \"Max Score\"\nFROM  anomaly_host_detail \nWHERE anomaly_host_detail.start_time BETWEEN $__from AND $__to\nGROUP BY anomaly_host_detail.unit_name;\n"
    }
   ]
  },
  {
   "title": "Anomalies for Host",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "select \ndistinct(anomaly_host_detail.unit_name) as \"Host\",\nanomaly_host_detail.start_time as \"Time\",\nanomaly_host_detail.id as \"Window\",\nanomaly_host_detail.anomalous_score as \"Anomaly Level\"\nFROM word_scores_by_time_window_and_template\nJOIN anomaly_host_detail ON anomaly_host_detail.id = time_window_id\nWHERE word_contribution > 0 and anomaly_host_detail.unit_name = '$Hostname'\n    AND anomaly_host_detail.start_time BETWEEN $__from AND $__to\nGROUP BY anomaly_host_detail.unit_name, anomaly_host_detail.id, anomaly_host_detail.start_time, anomaly_host_detail.anomalous_score;\n"
    }
   ]
  },
  {
   "title": "Word Cloud for Host",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT word_sentiment AS \"Tag/Words\",\r\n       sum(word_contribution) AS \"Count\"\r\nFROM word_scores_by_time_window_and_template\r\nJOIN anomaly_host_detail ON anomaly_host_detail.id = time_window_id\r\nWHERE word_contribution > 0 and anomaly_host_detail.unit_name = '$Hostname'\r\n    AND anomaly_host_detail.start_time BETWEEN $__from AND $__to\r\nGROUP BY word_sentiment;"
    }
   ]
  },
  {
   "title": "Log Templates for Host and Anomaly Contribution",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"Sample\", clean_template, a.Occur, a.Avg, a.Max\r\nFROM clean_templates\r\nINNER JOIN (SELECT \ttime_window_templates.template_id, \r\n\t\t\ttime_window_templates.template_version, \r\n\t\t\tCOUNT(time_window_templates.sentiment_contribution) as Occur,\r\n\t\t\tROUND(AVG(time_window_templates.sentiment_contribution)*100,2) as Avg,\r\n\t\t\tROUND(MAX(time_window_templates.sentiment_contribution)*100,2) as Max\r\nFROM anomaly_host_detail\r\nINNER JOIN time_window_templates\r\nON anomaly_host_detail.id = time_window_templates.time_window_id\r\nWHERE anomaly_host_detail.unit_name = '$Hostname' AND \r\n(anomaly_host_detail.start_time BETWEEN $__from AND $__to)\r\nAND time_window_templates.sentiment_contribution > 0.0\r\nGROUP BY template_id, template_version) a\r\nON clean_templates.id = a.template_id AND clean_templates.version = a.template_version;"
    }
   ]
  }
 ]
}