{
 "title": "Host Log Volume Interactive Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_window", "query": "0" },
   {
    "name": "template",
    "query": "\"\""
   },
   { "name": "Hostname", "query": "1" },
   { "name": "TemplateTable", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Host",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  unit_name as \"Host\", \n  sum(total_count) as \"# of Logs\"\nFROM\n  logs_by_host\nWHERE start_time BETWEEN $__from AND $__to\nGROUP by\nunit_name\nORDER by\nsum(total_count) desc;"
    }
   ]
  },
  {
   "title": "Log Volume by Host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time/1000 as \"time\",\n  unit_name as \"Host\", \n  sum(total_count)\nFROM\n  logs_by_host\nwhere start_time BETWEEN $__from AND $__to \nGROUP by\nstart_time, unit_name\nORDER by\nstart_time, sum(total_count) asc;\n"
    }
   ]
  },
  {
   "title": "Log Volume by Template",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT c.time, c.template, SUM(c.\"# of Logs\") as \"# of Logs\"\nFROM\n  (SELECT b.time,\n          b.\"Template_id\",\n          CASE\n              WHEN rank < 6 THEN rank\n              ELSE 6\n          END,\n          CASE\n          WHEN rank < 6 then b.\"Template_id\"\n          ELSE 'Others'\n          END as \"template\",\n          b.\"# of Logs\"\n   FROM\n     (SELECT *,\n             ROW_NUMBER() OVER (PARTITION BY TIME\n                                ORDER BY \"# of Logs\" DESC) AS rank\n      FROM\n        (SELECT start_time/1000 AS \"time\",\n                substr(TABLE_NAME, 16, 40) AS \"Template_id\",\n                sum(COUNT) AS \"# of Logs\"\n         FROM template_counts_host\n         WHERE unit_name='$Hostname'\n           AND start_time BETWEEN $__from AND $__to\n         GROUP BY start_time,\n                  TABLE_NAME\n         ORDER BY sum(COUNT) ASC) a) b) c\nGROUP BY c.time, c.template\nORDER BY c.time, SUM(c.\"# of Logs\") DESC;\n"
    }
   ]
  },
  {
   "title": "Number of Logs by Template",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\nconcat_ws('_', id, version) as \"Template id\",\n\"max\" as \"Sample record\",\nclean_template as \"Template\",\nsum(count) as \"# of Logs\"\nfrom\ntemplate_counts_host\nwhere\nunit_name='$Hostname' and start_time BETWEEN $__from AND $__to\nGroup by\n\"Template id\", \"Sample record\", clean_template\norder by\nsum(count) desc;\n"
    }
   ]
  },
  {
   "title": "Parsed Data from Anomalous Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM template_table_$TemplateTable \nINNER JOIN time_windows ON time_window_id = time_windows.id\nWHERE start_time BETWEEN $__from AND $__to;\n"
    }
   ]
  }
 ]
}