{
 "title": "SliceUpHomePage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Log_Template", "query": "%" },
   {
    "name": "LogTempLoad",
    "query": "select\ntemplate_id as \"Template\",\nmax_anomalous_score as \"Criticality\"\nFrom anom_highest_contrib_template\nwhere max_start_time BETWEEN $__from AND $__to\norder by \"Criticality\" DESC;"
   },
   { "name": "Ver", "query": "%" }
  ]
 },
 "panels": [
  {
   "title": "Logs and Anomalies Over Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Logs/Second" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time /1000 AS \"time\",\n  sum / 120 as \"# of logs per second\"\nFROM logs_over_time\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  start_time/1000 AS \"time\",\n  anomalous_score as \"Critical Anomaly Score\"\nFROM anomaly_host_detail\nwhere anomalous_score > 6\ngroup by start_time, anomalous_score\nORDER BY start_time\n"
    },
    {
     "rawSql": "SELECT\n  start_time/1000 AS \"time\",\n  anomalous_score as \"Important Anomaly Score\"\nFROM anomaly_host_detail\nwhere anomalous_score >= 3 and anomalous_score < 6\ngroup by start_time, anomalous_score\nORDER BY start_time\n"
    },
    {
     "rawSql": "SELECT\n  start_time/1000 AS \"time\",\n  anomalous_score as \"Low Anomaly Score\"\nFROM anomaly_host_detail\nwhere anomalous_score < 3\ngroup by start_time, anomalous_score\nORDER BY start_time\n"
    }
   ]
  },
  {
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT word_sentiment AS \"Tag/Words\",\r\n       sum(word_contribution) AS \"Count\"\r\nFROM word_scores_by_time_window_and_template\r\nJOIN time_windows ON word_scores_by_time_window_and_template.time_window_id = time_windows.id\r\nWHERE word_contribution > 0\r\n    AND time_windows.start_time BETWEEN $__from AND $__to\r\n    AND word_scores_by_time_window_and_template.template_id LIKE '$Log_Template%'\r\nGROUP BY word_sentiment;"
    }
   ]
  },
  {
   "title": "Anomalies by Highest Contributing Log Template",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT max(\"Anomaly Time\") AS \"Most Recent\",\n       max(anomalous_score) AS \"Criticality\",\n       count(time_window_id) AS \"Occurrences\",\n       template_id as \"Template\",\n       template_version as \"Version\"\nFROM\n    anom_detail_list\nWHERE \"Anomaly Time\" BETWEEN $__from AND $__to\nGROUP BY template_id,\n         template_version\nORDER BY \"Criticality\" DESC;\n"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \ndistinct(anomaly_host_detail.unit_name) as \"Host\"\nFROM time_window_templates\nJOIN anomaly_host_detail ON anomaly_host_detail.id = time_window_id\nWHERE template_id =  '$LogTempLoad'\n  AND template_version = '$Ver'\n  AND model_id = 4\n  AND sentiment_contribution > 0\n  AND start_time BETWEEN $__from AND $__to;"
    }
   ]
  },
  {
   "title": "Anomaly Detail List",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\"Anomaly Time\",\r\ntime_window_id as \"Window\",\r\ntemplate_id as \"Template\",\r\ntemplate_version as \"Version\",\r\nanomalous_score as \"Criticality\"\r\nFROM anom_detail_list \r\nWHERE \"Anomaly Time\" BETWEEN $__from AND $__to and template_id = '$LogTempLoad' and template_version = '$Ver';"
    }
   ]
  },
  {
   "title": "Highest Contributing Log Template",
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  clean_template, record\nFROM clean_templates \n  INNER JOIN log_examples \n    ON (clean_templates.id = log_examples.template_id AND clean_templates.version = log_examples.template_version)\nwhere id = '$LogTempLoad' and version = '$Ver';\n"
    }
   ]
  }
 ]
}