{
 "title": "Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Storage Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now () AS \"time\",\n  sum(total_count)*450 as \"With SliceUp\"\nFROM anomaly_host_detail\nwhere start_time BETWEEN $__from AND $__to;"
    },
    {
     "rawSql": "SELECT\n  now () AS \"time\",\n  sum(sum) * 450 as \"Without SliceUp\"\nFROM logs_over_time\nwhere start_time BETWEEN $__from AND $__to;\n"
    },
    {
     "rawSql": "SELECT (1-(A.sum / B.sum))*100 AS \"Percent Savings\"\nFROM   (SELECT\n  sum(total_count)\nFROM anomaly_host_detail where anomaly_host_detail.start_time BETWEEN $__from AND $__to) A\n     ,(SELECT\n  sum(sum)\nFROM logs_over_time where logs_over_time.start_time BETWEEN $__from AND $__to) B;\n"
    }
   ]
  },
  {
   "title": "Anomaly Counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n count(id) as \"Critical Anomaly\"\nFROM anomaly_host_detail\nWHERE\n  anomalous_score > 6 and start_time BETWEEN $__from AND $__to\n"
    },
    {
     "rawSql": "SELECT\n  count(id) as \"Important Anomaly\"\nFROM anomaly_host_detail\nWHERE\n  anomalous_score > 3.7 AND\n  anomalous_score < 6 and start_time BETWEEN $__from AND $__to\n"
    },
    {
     "rawSql": "SELECT\n  count(id) as \"Low Anomaly\"\nFROM anomaly_host_detail\nWHERE\n  anomalous_score > 0 and anomalous_score < 3.7 and start_time BETWEEN $__from AND $__to\n"
    }
   ]
  },
  {
   "title": "Logs Analyzed over Time Period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum as \"# of Logs\"\nFROM logs_over_time\nwhere start_time BETWEEN $__from AND $__to\n\n"
    },
    {
     "rawSql": "SELECT\n  avg(sum)/10 as \"Logs/sec\"\nFROM logs_over_time\nwhere start_time BETWEEN $__from AND $__to\n"
    }
   ]
  }
 ]
}