{
 "title": "Time Window Template Details",
 "time": { "from": "2020-07-26T23:18:30.000Z", "to": "2020-07-27T17:20:10.000Z" },
 "templating": {
  "list": [
   { "name": "template_id", "query": "postgres" },
   { "name": "template_version", "query": "postgres" },
   { "name": "time_window_id", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Template created from log files",
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  template\r\nFROM templates\r\nwhere id = '$template_id' and version = $template_version;"
    }
   ]
  },
  {
   "title": "Log Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select synthetic_record as \"Log Records\", record_score \nfrom salient_records\nwhere table_name = 'template_table_${template_id}_${template_version}' and time_window_id = ${time_window_id}\nORDER BY record_score;\n"
    }
   ]
  },
  {
   "title": "Parsed data from Template",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select *\nfrom template_table_${template_id}_${template_version}\nwhere time_window_id=${time_window_id};"
    }
   ]
  },
  {
   "title": "Words Associated to Template",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT word_sentiment AS \"Tag/Words\",\n       sum(word_contribution) AS \"Count\"\nFROM word_scores_by_time_window_and_template\nJOIN time_windows ON word_scores_by_time_window_and_template.time_window_id = time_windows.id\nWHERE word_contribution > 0\n    AND time_windows.start_time BETWEEN $__from AND $__to\n    AND word_scores_by_time_window_and_template.template_id = '$template_id'\nGROUP BY word_sentiment;\n"
    }
   ]
  }
 ]
}