{
 "title": "Word Cloud Filter",
 "tags": [ "Direct" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Log_Template", "query": "%" },
   { "name": "SelectedWord", "query": "%" },
   { "name": "TemplateTable", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Word Cloud Terms",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT word_sentiment AS \"Words\",\n       sum(word_contribution) AS \"Weighted Score\",\n       sum(word_contribution)/count(template_id) as \"Avg Score\",\n\tcount(template_id) as \"# of Logs\"\nFROM word_scores_by_time_window_and_template\nJOIN time_windows ON word_scores_by_time_window_and_template.time_window_id = time_windows.id\nWHERE word_contribution > 0\n    AND time_windows.start_time BETWEEN $__from AND $__to\nGROUP BY word_sentiment;\n"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": " SELECT DISTINCT analized_units.unit_name as \"Host\"\r\nFROM word_scores_by_time_window_and_template\r\nINNER JOIN time_windows ON time_window_id = time_windows.id\r\nINNER JOIN analized_units ON analized_units.id = entity_analyzed_id\r\nWHERE word_sentiment = '$SelectedWord'\r\n  AND (\r\n       time_windows.start_time BETWEEN $__from AND $__to);"
    }
   ]
  },
  {
   "title": "Templates",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT concat_ws('_', clean_templates.id, clean_templates.version) AS \"Template id\",\r\ntemplate_example_single.max AS \"Sample record\",\r\nclean_templates.clean_template as \"Template\"\r\nFROM word_scores_by_time_window_and_template\r\nINNER JOIN time_windows ON time_window_id = time_windows.id\r\nINNER JOIN clean_templates ON (word_scores_by_time_window_and_template.template_id = clean_templates.id AND word_scores_by_time_window_and_template.template_version = clean_templates.version)\r\nINNER JOIN template_example_single ON (template_example_single.template_id = clean_templates.id AND template_example_single.template_version = clean_templates.version)\r\nWHERE word_sentiment = '$SelectedWord'\r\n  AND (\r\n       time_windows.start_time BETWEEN $__from AND $__to)\r\ngroup by clean_template, template_example_single.max, \"Template id\";"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM template_table_$TemplateTable \nINNER JOIN time_windows ON time_window_id = time_windows.id\nWHERE start_time BETWEEN $__from AND $__to;"
    }
   ]
  }
 ]
}